In [70]:
import numpy as np

### 1

In [72]:
one_ten = np.arange(1,10+1,1)
print("1 - 10" ,one_ten)

1 - 10 [ 1  2  3  4  5  6  7  8  9 10]


In [73]:
half_five = np.arange(0.5,5.25,0.25)
print("0.5 - 5 ",half_five)

0.5 - 5  [0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75
 4.   4.25 4.5  4.75 5.  ]


#### 2

In [75]:
ten_1line = np.zeros(10)
print("10 in 1 line ", ten_1line)

10 in 1 line  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [76]:
twelv_3_4 = np.zeros((3,4),dtype = int)
print(twelv_3_4)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


#### 3

In [78]:
items_5 = np.linspace(2,12,5,dtype=float)
print(items_5)

[ 2.   4.5  7.   9.5 12. ]


In [79]:
items_4 = np.linspace(3,9,4,dtype=int)
print(items_4)

[3 5 7 9]


#### 4

In [81]:
random_2_4 = np.random.rand(2, 4)
print(random_2_4)

[[0.13031048 0.95269545 0.46825599 0.32626486]
 [0.66606832 0.89480165 0.01869786 0.02690456]]


In [82]:
np.random.randint(10, 20, (3,3))


array([[12, 11, 12],
       [15, 15, 10],
       [18, 13, 10]])

In [83]:
re_shape_a = np.reshape(random_2_4,(1,8))
print(re_shape_a)

[[0.13031048 0.95269545 0.46825599 0.32626486 0.66606832 0.89480165
  0.01869786 0.02690456]]


#### in the new shape we need to unsure that have same nmbers of items like the original

#### 5) "np.random.seed(num that be anchor)" allways when we random numbers the numbers will be the same
#### the advantage in using "seed" is that we can reuse the same result over and over and still be consistency